### ISSUE TITLE
Trellis und neuste Version von Virtualbox 6.1.28

### ISSUE THREAD

**Issue by whatwouldmarvindo** [dol-lab/trellis#1]
## Fehler
[Wie in diesem Ticket beschrieben](https://www.virtualbox.org/ticket/20626) funktioniert das Setup mit Trellis in Spaces und der neusten Version von Virtualbox leider nicht. 

**Fehldercode:**
`VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)`

## Pflaster
Ein Downgrade auf die Version 6.1.26 hat das Problem bei mir (und den anderen im Forum) gelöst. Ältere Builds von Virtualbox können [hier gedownloaded werden](https://www.virtualbox.org/wiki/Download_Old_Builds_6_1)

## Fix

Ich bin mir nicht ganz sicher wo genau das Problem jetzt liegt. Vielleicht sollte kurzfristig die README angepasst werden und danach das eigentliche Problem gelöst werden falls das nicht zu umfangreich ist? Ich kann die README gerne anpassen wenn das in Ordnung ist.

**Comment by schuhwerk** [comment]
Hi Marvin. Vielen Dank für den Hinweis. Die Idee mit der readme ist super, gerne dazupacken!
